### ISSUE TITLE
gauss_fmtc_blur needlessly resizes the clip

### ISSUE THREAD

**Issue by ghost** [Setsugennoao/vs-rgtools#32]
Gaussian kernel is non-interpolatory meaning a same-res resample can be performed to create a blur effect, the current function is instead resizing with bilinear and gauss which not only hurts performance but also quality.

**Comment by Setsugennoao** [comment]
How would that translate in fmtc params?

**Comment by Setsugennoao** [comment]
The boundaries for fmtc are 1-100 for a1.

This translates to ~0.26 to ~2.6 which is handled by the convolution, which does the exact same operation as the fmtc code (but with hbd support and no conversions whatsoever)

sigma=0.2685791355344793, a1=99.99999999999996
sigma=2.6857913553447923, a1=1.0000000000000002

tldr; it's not useless since it doesn't support high sigmas.

**Comment by Setsugennoao** [comment]
For the record, when sigma is lower than 1 / 3, it doesn't do anything (a1 > 64).
When a1 is smaller or equal than taps, a1 acts like it's 1.
So you can't even use it for the 0.26-0.333 range.
